namespace DeezSpoTag.Web.Services.AutoTag;

public static class BandcampGenres
{
    private static readonly HashSet<string> Genres = new(StringComparer.OrdinalIgnoreCase)
    {
        "pop rock",
        "house",
        "vocal",
        "experimental",
        "punk",
        "synth-pop",
        "alternative rock",
        "techno",
        "disco",
        "soul",
        "indie rock",
        "ambient",
        "hardcore",
        "folk",
        "country",
        "hard rock",
        "ballad",
        "electro",
        "rock & roll",
        "chanson",
        "trance",
        "heavy metal",
        "psychedelic rock",
        "folk rock",
        "downtempo",
        "romantic",
        "soundtrack",
        "classic rock",
        "noise",
        "schlager",
        "prog rock",
        "funk",
        "easy listening",
        "black metal",
        "tech house",
        "new wave",
        "blues rock",
        "deep house",
        "rhythm & blues",
        "industrial",
        "euro house",
        "drum n bass",
        "death metal",
        "classical",
        "progressive house",
        "soft rock",
        "abstract",
        "garage rock",
        "minimal",
        "europop",
        "gospel",
        "acoustic",
        "thrash",
        "swing",
        "baroque",
        "big band",
        "modern",
        "dub",
        "country rock",
        "breakbeat",
        "rnb/swing",
        "contemporary jazz",
        "drone",
        "progressive trance",
        "indie pop",
        "dancehall",
        "opera",
        "idm",
        "breaks",
        "contemporary",
        "reggae",
        "art rock",
        "african",
        "fusion",
        "dark ambient",
        "gangsta",
        "hard trance",
        "doom metal",
        "avantgarde",
        "post-punk",
        "pop rap",
        "rockabilly",
        "religious",
        "beat",
        "roots reggae",
        "electro house",
        "jazz-funk",
        "acid",
        "lo-fi",
        "instrumental",
        "comedy",
        "score",
        "dance-pop",
        "leftfield",
        "grindcore",
        "ska",
        "dubstep",
        "theme",
        "soul-jazz",
        "post rock",
        "hip hop",
        "power pop",
        "psy-trance",
        "spoken word",
        "glam",
        "modern classical",
        "bop",
        "goth rock",
        "hard house",
        "salsa",
        "new age",
        "jazz-rock",
        "conscious",
        "bolero",
        "free improvisation",
        "trip hop",
        "latin jazz",
        "italo-disco",
        "musical",
        "emo",
        "stoner rock",
        "ebm",
        "cumbia",
        "hard bop",
        "shoegaze",
        "surf",
        "garage house",
        "free jazz",
        "mpb",
        "contemporary r&b",
        "j-pop",
        "doo wop",
        "jungle",
        "oi",
        "field recording",
        "story",
        "cool jazz",
        "volksmusik",
        "samba",
        "happy hardcore",
        "hardstyle",
        "post bop",
        "uk garage",
        "tribal",
        "tango",
        "pop punk",
        "bluegrass",
        "laÃ¯kÃ³",
        "celtic",
        "radioplay",
        "darkwave",
        "synthwave",
        "novelty",
        "smooth jazz",
        "eurodance",
        "vaporwave",
        "italodance",
        "flamenco",
        "grunge",
        "polka",
        "dixieland",
        "arena rock",
        "future jazz",
        "symphonic rock",
        "metalcore",
        "southern rock",
        "latin",
        "hardcore hip-hop",
        "parody",
        "choral",
        "nu metal",
        "aor",
        "glitch",
        "progressive metal",
        "hindustani",
        "rumba",
        "trap",
        "gabber",
        "space rock",
        "cha-cha",
        "krautrock",
        "hi nrg",
        "dub techno",
        "thug rap",
        "speed metal",
        "bossa nova",
        "power metal",
        "merengue",
        "breakcore",
        "audiobook",
        "bollywood",
        "acid house",
        "reggae-pop",
        "poetry",
        "power electronics",
        "neo-classical",
        "boom bap",
        "musique concrÃ¨te",
        "mod",
        "harsh noise wall",
        "electric blues",
        "freestyle",
        "boogie",
        "acid jazz",
        "avant-garde jazz",
        "jazzy hip-hop",
        "bossanova",
        "renaissance",
        "chiptune",
        "country blues",
        "mambo",
        "marches",
        "big beat",
        "tribal house",
        "post-hardcore",
        "sludge metal",
        "interview",
        "kayÅkyoku",
        "ranchera",
        "math rock",
        "bass music",
        "broken beat",
        "dungeon synth",
        "rocksteady",
        "calypso",
        "chicago blues",
        "modal",
        "neofolk",
        "minimal techno",
        "ethereal",
        "education",
        "psychedelic",
        "nu-disco",
        "afrobeat",
        "indian classical",
        "lounge",
        "afro-cuban",
        "grime",
        "light music",
        "neo soul",
        "crust",
        "goa trance",
        "hip-house",
        "berlin-school",
        "lovers rock",
        "ragtime",
        "impressionist",
        "guaracha",
        "Ã©ntekhno",
        "operetta",
        "g-funk",
        "britpop",
        "rhythmic noise",
        "psychobilly",
        "gothic metal",
        "chillwave",
        "brass band",
        "euro-disco",
        "cut-up/dj",
        "nursery rhymes",
        "neo-romantic",
        "mandopop",
        "ragga",
        "pacific",
        "medieval",
        "tech trance",
        "dialogue",
        "son",
        "symphonic metal",
        "speedcore",
        "melodic death metal",
        "ragga hiphop",
        "canzone napoletana",
        "guaguancÃ³",
        "deep techno",
        "twist",
        "space-age",
        "honky tonk",
        "promotional",
        "goregrind",
        "video game music",
        "fado",
        "eurobeat",
        "nordic",
        "educational",
        "political",
        "funk metal",
        "music hall",
        "military",
        "highlife",
        "melodic hardcore",
        "acid rock",
        "makina",
        "hard techno",
        "soca",
        "jazzdance",
        "afro-cuban jazz",
        "dream pop",
        "new jack swing",
        "zouk",
        "speech",
        "mariachi",
        "atmospheric black metal",
        "soukous",
        "monolog",
        "folk metal",
        "sound collage",
        "piano blues",
        "deathcore",
        "delta blues",
        "hawaiian",
        "k-pop",
        "modern electric blues",
        "romani",
        "horrorcore",
        "new beat",
        "reggaeton",
        "freetekno",
        "cubano",
        "witch house",
        "hands up",
        "noisecore",
        "viking metal",
        "gypsy jazz",
        "luk thung",
        "public broadcast",
        "jumpstyle",
        "bubblegum",
        "texas blues",
        "forrÃ³",
        "post-metal",
        "italo house",
        "harmonica blues",
        "boogaloo",
        "coldwave",
        "city pop",
        "speed garage",
        "no wave",
        "special effects",
        "cajun",
        "post-modern",
        "therapy",
        "norteÃ±o",
        "j-rock",
        "sound art",
        "pub rock",
        "p.funk",
        "bhangra",
        "jump blues",
        "oratorio",
        "vallenato",
        "enka",
        "illbient",
        "yÃ©-yÃ©",
        "descarga",
        "corrido",
        "bassline",
        "porro",
        "pachanga",
        "rebetiko",
        "hillbilly",
        "louisiana blues",
        "brit pop",
        "electroacoustic",
        "guajira",
        "tejano",
        "boogie woogie",
        "beguine",
        "screw",
        "donk",
        "son montuno",
        "karaoke",
        "depressive black metal",
        "raÃ¯",
        "min'yÅ",
        "nueva cancion",
        "juke",
        "charanga",
        "deathrock",
        "sÃ©ga",
        "cloud rap",
        "power violence",
        "klezmer",
        "industrial metal",
        "technical death metal",
        "chinese classical",
        "western swing",
        "copla",
        "sermon",
        "crunk",
        "technical",
        "dj battle tool",
        "compas",
        "ghetto",
        "aboriginal",
        "cantopop",
        "disco polo",
        "groove metal",
        "nÃ©pzene",
        "andean music",
        "swingbeat",
        "tropical house",
        "electroclash",
        "pasodoble",
        "bounce",
        "danzon",
        "free funk",
        "bachata",
        "bayou funk",
        "health-fitness",
        "batucada",
        "zydeco",
        "funeral doom metal",
        "minneapolis sound",
        "turntablism",
        "appalachian music",
        "conjunto",
        "halftime",
        "catalan music",
        "jangle pop",
        "pornogrind",
        "levenslied",
        "sea shanties",
        "quechua",
        "carnatic",
        "mÃºsica criolla",
        "movie effects",
        "steel band",
        "progressive breaks",
        "skiffle",
        "hokkien pop",
        "lambada",
        "swamp pop",
        "early",
        "ghetto house",
        "liscio",
        "ethno-pop",
        "sound poetry",
        "j-core",
        "pipe & drum",
        "doomcore",
        "miami bass",
        "axÃ©",
        "footwork",
        "cretan",
        "bleep",
        "plena",
        "gamelan",
        "indo-pop",
        "baiÃ£o",
        "schranz",
        "horror rock",
        "ottoman classical",
        "choro",
        "mizrahi",
        "britcore",
        "kwaito",
        "persian classical",
        "musette",
        "nueva trova",
        "erotic",
        "glitch hop",
        "zarzuela",
        "trova",
        "ghazal",
        "barbershop",
        "zamba",
        "basque music",
        "samba-canÃ§Ã£o",
        "chamamÃ©",
        "public service announcement",
        "uk street soul",
        "go-go",
        "group sounds",
        "east coast blues",
        "dangdut",
        "memphis blues",
        "ndw",
        "chacarera",
        "beatdown",
        "bengali music",
        "luk krung",
        "huayno",
        "neo trance",
        "tamil film music",
        "ghettotech",
        "twelve-tone",
        "kaseko",
        "reggae gospel",
        "joropo",
        "qawwali",
        "mo lam",
        "gaita",
        "k-rock",
        "chutney",
        "dub poetry",
        "hyphy",
        "cabaret",
        "timba",
        "hiplife",
        "marimba",
        "rock opera",
        "morna",
        "piedmont blues",
        "cape jazz",
        "keroncong",
        "gogo",
        "uk funky",
        "guarania",
        "favela funk",
        "mento",
        "andalusian classical",
        "balearic",
        "medical",
        "ryÅ«kÅka",
        "baltimore club",
        "nháº¡c vÃ ng",
        "overtone singing",
        "jibaro",
        "sephardic",
        "phleng phuea chiwit",
        "jota",
        "maloya",
        "phonk",
        "salegy",
        "griot",
        "hard beat",
        "dark jazz",
        "lento violento",
        "marcha carnavalesca",
        "hyperpop",
        "beatbox",
        "sertanejo",
        "thai classical",
        "serial",
        "villancicos",
        "mugham",
        "spirituals",
        "bomba",
        "gagaku",
        "mbalax",
        "skweee",
        "candombe",
        "galician traditional",
        "nerdcore techno",
        "funanaÌ",
        "cuatro",
        "vaudeville",
        "sÃ¡mi music",
        "ballroom",
        "sonero",
        "carimbÃ³",
        "kizomba",
        "aguinaldo",
        "shaabi",
        "champeta",
        "stride",
        "caipira",
        "zemer ivri",
        "electro swing",
        "break-in",
        "baroque pop",
        "seresta",
        "jug band",
        "philippine classical",
        "yemenite jewish",
        "funkot",
        "jersey club",
        "junkanoo",
        "mouth music",
        "rune singing",
        "gwo ka",
        "cobla",
        "nÃ©o kyma",
        "bambuco",
        "moombahton",
        "piobaireachd",
        "hill country blues",
        "taarab",
        "occitan",
        "filk",
        "korean court music",
        "progressive bluegrass",
        "rapso",
        "waiata",
        "bubbling",
        "cambodian classical",
        "bangladeshi classical",
        "milonga",
        "lao music",
        "rÅkyoku",
        "guggenmusik",
        "klasik",
        "gqom",
        "kuduro",
        "gÄ§ana",
        "bongo flava",
        "motswako",
        "spaza",
        "azonto",
        "shidaiqu",
        "sean-nÃ³s",
        "shoegazer",
        "trallalero",
        "rock",
        "electronic",
        "pop",
        "folk, world, & country",
        "jazz",
        "funk / soul",
        "stage & screen",
        "blues",
        "non-music",
        "children's",
        "brass & military",
        "2 tone",
        "2-step",
        "aak",
        "aboio",
        "abstract hip hop",
        "acid breaks",
        "acid house",
        "acid jazz",
        "acid rock",
        "acid techno",
        "acid trance",
        "acidcore",
        "acousmatic",
        "acoustic blues",
        "acoustic chicago blues",
        "acoustic rock",
        "acoustic texas blues",
        "afoxÃª",
        "african blues",
        "afro house",
        "afro rock",
        "afro trap",
        "afro-cuban jazz",
        "afro-funk",
        "afro-jazz",
        "afrobeat",
        "afrobeats",
        "afroswing",
        "agbadza",
        "agbekor",
        "aggrotech",
        "aita",
        "akishibu-kei",
        "al jeel",
        "algerian chaabi",
        "algorave",
        "alpenrock",
        "alternative country",
        "alternative dance",
        "alternative folk",
        "alternative hip hop",
        "alternative metal",
        "alternative pop",
        "alternative punk",
        "alternative rock",
        "amapiano",
        "ambasse bey",
        "ambient",
        "ambient americana",
        "ambient dub",
        "ambient house",
        "ambient noise wall",
        "ambient pop",
        "ambient techno",
        "ambient trance",
        "american primitive guitar",
        "americana",
        "anarcho-punk",
        "anatolian rock",
        "andalusian classical",
        "anti-folk",
        "aor",
        "apala",
        "appalachian folk",
        "arabesk",
        "arabesk rap",
        "arena rock",
        "arrocha",
        "arrocha funk",
        "arrocha sertanejo",
        "arrochadeira",
        "ars antiqua",
        "ars nova",
        "ars subtilior",
        "art pop",
        "art punk",
        "art rock",
        "art song",
        "artcore",
        "asmr",
        "assiko",
        "atmospheric black metal",
        "atmospheric drum and bass",
        "atmospheric sludge metal",
        "audio drama",
        "avant-folk",
        "avant-garde",
        "avant-garde jazz",
        "avant-garde metal",
        "avant-garde pop",
        "avant-prog",
        "avtorskaya pesnya",
        "axÃ©",
        "bachata",
        "bagad",
        "baiÃ£o",
        "baila",
        "baisha xiyue",
        "baithak gana",
        "bakersfield sound",
        "balani show",
        "balearic beat",
        "balearic trance",
        "balinese gamelan",
        "balitaw",
        "ballad",
        "ballet",
        "ballroom house",
        "baltimore club",
        "bambuco",
        "banda sinaloense",
        "bandari",
        "bandinha",
        "barbershop",
        "bard rock",
        "bardcore",
        "baroque",
        "baroque pop",
        "bass house",
        "bassline",
        "batida",
        "batidÃ£o romÃ¢ntico",
        "battle rap",
        "batucada",
        "batuque",
        "baul gaan",
        "beat bruxaria",
        "beat music",
        "beat poetry",
        "beatdown hardcore",
        "bebop",
        "bedroom pop",
        "beijing opera",
        "bÃ©lÃ©",
        "bend-skin",
        "benga",
        "benna",
        "bÃ©rite club",
        "berlin school",
        "bhangra",
        "big band",
        "big beat",
        "big room house",
        "big room trance",
        "biguine",
        "bikutsi",
        "binaural beats",
        "bit music",
        "bitpop",
        "black 'n' roll",
        "black ambient",
        "black metal",
        "black noise",
        "blackened crust",
        "blackened death metal",
        "blackgaze",
        "bleep techno",
        "blue-eyed soul",
        "bluegrass",
        "bluegrass gospel",
        "blues",
        "blues rock",
        "bocet",
        "boduberu",
        "boedra",
        "bogino duu",
        "bolero",
        "bolero espaÃ±ol",
        "bolero son",
        "bolero-beat",
        "bomba",
        "bomba del chota",
        "bongo flava",
        "boogaloo",
        "boogie",
        "boogie rock",
        "boogie-woogie",
        "boom bap",
        "bossa nova",
        "bounce",
        "bouncy techno",
        "bouyon",
        "brazilian bass",
        "break-in",
        "breakbeat",
        "breakbeat hardcore",
        "breakbeat kota",
        "breakcore",
        "breaks",
        "breakstep",
        "brega",
        "brega calypso",
        "brega funk",
        "brill building",
        "brit funk",
        "britcore",
        "british blues",
        "british folk rock",
        "british rhythm & blues",
        "britpop",
        "bro-country",
        "broken beat",
        "broken transmission",
        "brostep",
        "brutal death metal",
        "brutal prog",
        "bubblegum bass",
        "bubblegum dance",
        "bubblegum pop",
        "bubbling",
        "bubbling house",
        "budots",
        "bullerengue",
        "burger-highlife",
        "burmese mono",
        "burmese stereo",
        "burning spirits",
        "bytebeat",
        "c-pop",
        "c86",
        "ca trÃ¹",
        "cabaret",
        "cabo zouk",
        "cadence lypso",
        "cadence rampa",
        "cáº£i lÆ°Æ¡ng",
        "cajun",
        "cakewalk",
        "Äalgija",
        "calypso",
        "campursari",
        "campus folk",
        "canciÃ³n melÃ³dica",
        "candombe",
        "candombe beat",
        "cantata",
        "cante alentejano",
        "canterbury scene",
        "canto a lo poeta",
        "canto cardenche",
        "cantonese opera",
        "cantopop",
        "cantoria",
        "cantu a tenore",
        "canzone napoletana",
        "canzone neomelodica",
        "cape breton fiddling",
        "cape jazz",
        "carimbÃ³",
        "carnatic classical",
        "carnavalito",
        "carranga",
        "celtic",
        "celtic electronica",
        "celtic metal",
        "celtic new age",
        "celtic punk",
        "celtic rock",
        "central asian throat singing",
        "chacarera",
        "chachachÃ¡",
        "chalga",
        "chamamÃ©",
        "chamarrita aÃ§oriana",
        "chamarrita rioplatense",
        "chamber folk",
        "chamber pop",
        "champeta",
        "changÃ¼Ã­",
        "chanson Ã  texte",
        "chanson franÃ§aise",
        "chanson rÃ©aliste",
        "charanga",
        "chazzanut",
        "chicago blues",
        "chicago bop",
        "chicago house",
        "chicago soul",
        "chicano rap",
        "chilena",
        "chillout",
        "chillstep",
        "chillsynth",
        "chillwave",
        "chimurenga",
        "chinese opera",
        "chinese revolutionary opera",
        "chipmunk soul",
        "chiptune",
        "chopped and screwed",
        "choro",
        "chotis madrileÃ±o",
        "christian hip hop",
        "christian metal",
        "christian rock",
        "christmas music",
        "chutney",
        "chutney soca",
        "cilokaq",
        "ciranda",
        "city pop",
        "classic blues",
        "classic country",
        "classic jazz",
        "classic rock",
        "classical",
        "classical crossover",
        "close harmony",
        "cloud rap",
        "club",
        "coco",
        "coladeira",
        "coldwave",
        "colindÄ",
        "colour bass",
        "comedy",
        "comedy hip hop",
        "comedy rock",
        "comfy synth",
        "compas",
        "complextro",
        "conga",
        "congolese rumba",
        "conscious hip hop",
        "contemporary christian",
        "contemporary classical",
        "contemporary country",
        "contemporary folk",
        "contemporary gospel",
        "contemporary jazz",
        "contemporary r&b",
        "contra",
        "cool jazz",
        "coon song",
        "copla",
        "corrido",
        "corrido tumbado",
        "country",
        "country and irish",
        "country blues",
        "country boogie",
        "country folk",
        "country gospel",
        "country pop",
        "country rap",
        "country rock",
        "country soul",
        "country yodeling",
        "countrypolitan",
        "coupÃ©-dÃ©calÃ©",
        "cowpunk",
        "crime jazz",
        "crossbreed",
        "crossover jazz",
        "crossover prog",
        "crossover thrash",
        "crunk",
        "crunkcore",
        "crust punk",
        "csÃ¡rdÃ¡s",
        "cuarteto",
        "cubatÃ³n",
        "cueca",
        "cumbia",
        "cumbia argentina",
        "cumbia mexicana",
        "cumbia norteÃ±a mexicana",
        "cumbia peruana",
        "cumbia pop",
        "cumbia santafesina",
        "cumbia sonidera",
        "cumbia turra",
        "cumbia villera",
        "cuplÃ©",
        "currulao",
        "cyber metal",
        "cybergrind",
        "cyberpunk",
        "d-beat",
        "dabke",
        "dance",
        "dance-pop",
        "dance-punk",
        "dance-rock",
        "dancefloor drum and bass",
        "dancehall",
        "dangak",
        "dangdut",
        "danmono",
        "dansband",
        "danzÃ³n",
        "dark ambient",
        "dark cabaret",
        "dark electro",
        "dark folk",
        "dark jazz",
        "dark psytrance",
        "dark wave",
        "darkcore",
        "darkstep",
        "darksynth",
        "death 'n' roll",
        "death industrial",
        "death metal",
        "death-doom metal",
        "deathcore",
        "deathgrind",
        "deathrock",
        "deathstep",
        "deconstructed club",
        "deep funk",
        "deep house",
        "deep soul",
        "deep tech",
        "deep techno",
        "delta blues",
        "dembow",
        "dennery segment",
        "denpa",
        "depressive black metal",
        "descarga",
        "desert blues",
        "desert rock",
        "detroit techno",
        "detroit trap",
        "dhaanto",
        "dhrupad",
        "digicore",
        "digital cumbia",
        "digital fusion",
        "digital hardcore",
        "dimotiko",
        "dirty south",
        "disco",
        "disco polo",
        "dissonant death metal",
        "diva house",
        "dixieland",
        "djanba",
        "djent",
        "dobrado",
        "doina",
        "dongjing",
        "donk",
        "donosti sound",
        "doo-wop",
        "doom metal",
        "doomcore",
        "doskpop",
        "downtempo",
        "dream pop",
        "dream trance",
        "dreampunk",
        "drift phonk",
        "drill",
        "drill and bass",
        "drone",
        "drone metal",
        "drum and bass",
        "drumfunk",
        "drumless hip hop",
        "drumstep",
        "dub",
        "dub poetry",
        "dub techno",
        "dubstep",
        "dubstyle",
        "dubwise",
        "duma",
        "dunedin sound",
        "dungeon sound",
        "dungeon synth",
        "duranguense",
        "dutch house",
        "eai",
        "east coast hip hop",
        "easy listening",
        "easycore",
        "ebm",
        "edm",
        "electric blues",
        "electric texas blues",
        "electro",
        "electro house",
        "electro latino",
        "electro swing",
        "electro-disco",
        "electro-funk",
        "electro-industrial",
        "electroacoustic",
        "electroclash",
        "electronic",
        "electronic rock",
        "electronica",
        "electronicore",
        "electropop",
        "electropunk",
        "electrotango",
        "eleki",
        "embolada",
        "emo",
        "emo pop",
        "emo rap",
        "emocore",
        "emoviolence",
        "enka",
        "Ã©ntekhno",
        "epic collage",
        "epic doom metal",
        "estrada",
        "ethereal wave",
        "ethio-jazz",
        "euphoric hardstyle",
        "euro house",
        "euro-disco",
        "euro-trance",
        "eurobeat",
        "eurodance",
        "europop",
        "euskal kantagintza berria",
        "exotica",
        "experimental",
        "experimental big band",
        "experimental electronic",
        "experimental hip hop",
        "experimental rock",
        "extratone",
        "fado",
        "fado de coimbra",
        "fairy tale",
        "famo",
        "fandango",
        "fandango caiÃ§ara",
        "fantezi",
        "festival progressive house",
        "festival trap",
        "fidget house",
        "field recording",
        "filin",
        "filk",
        "filmi",
        "finnish tango",
        "flamenco",
        "flamenco jazz",
        "flamenco pop",
        "flashcore",
        "flex dance music",
        "florida breaks",
        "fm synthesis",
        "folk",
        "folk metal",
        "folk pop",
        "folk punk",
        "folk rock",
        "folkhop",
        "folktronica",
        "fon leb",
        "footwork",
        "footwork jungle",
        "forrÃ³",
        "forrÃ³ eletrÃ´nico",
        "forrÃ³ universitÃ¡rio",
        "freak folk",
        "freakbeat",
        "free folk",
        "free improvisation",
        "free jazz",
        "free tekno",
        "freeform hardcore",
        "freestyle",
        "french electro",
        "french house",
        "frenchcore",
        "frevo",
        "fuji",
        "full-on",
        "funanÃ¡",
        "funeral doom metal",
        "fungi",
        "funk",
        "funk carioca",
        "funk mandelÃ£o",
        "funk melody",
        "funk metal",
        "funk ostentaÃ§Ã£o",
        "funk proibidÃ£o",
        "funk rock",
        "funknejo",
        "funkot",
        "funktronica",
        "funky house",
        "future bass",
        "future bounce",
        "future core",
        "future funk",
        "future garage",
        "future house",
        "future rave",
        "futurepop",
        "g-funk",
        "g-house",
        "gabber",
        "gaelic psalm singing",
        "gagaku",
        "gagok",
        "gaita zuliana",
        "gambang kromong",
        "gamelan",
        "gamelan angklung",
        "gamelan beleganjur",
        "gamelan degung",
        "gamelan gender wayang",
        "gamelan gong gede",
        "gamelan gong kebyar",
        "gamelan jegog",
        "gamelan joged bumbung",
        "gamelan salendro",
        "gamelan sekaten",
        "gamelan selunding",
        "gamelan semar pegulingan",
        "gamelan siteran",
        "gangsta rap",
        "garage house",
        "garage punk",
        "garage rock",
        "garage rock revival",
        "garba",
        "genge",
        "gÄ§ana",
        "ghazal",
        "ghetto house",
        "ghettotech",
        "ginan",
        "glam",
        "glam metal",
        "glam punk",
        "glam rock",
        "glitch",
        "glitch hop",
        "glitch pop",
        "gnawa",
        "go-go",
        "goa trance",
        "gondang",
        "goombay",
        "goregrind",
        "gorenoise",
        "gospel",
        "gospel reggae",
        "gothic",
        "gothic country",
        "gothic metal",
        "gothic rock",
        "gqom",
        "grebo",
        "gregorian chant",
        "grime",
        "grindcore",
        "griot",
        "groove metal",
        "group sounds",
        "grunge",
        "guaguancÃ³",
        "guajira",
        "guaracha",
        "guaracha edm",
        "guarania",
        "guided meditation",
        "gumbe",
        "guoyue",
        "gwo ka",
        "gypsy jazz",
        "gypsy punk",
        "habanera",
        "haitian vodou drumming",
        "halftime",
        "hambo",
        "hamburger schule",
        "hands up",
        "happy hardcore",
        "harawi",
        "hard bop",
        "hard drum",
        "hard house",
        "hard nrg",
        "hard rock",
        "hard trance",
        "hard trap",
        "hardbag",
        "hardbass",
        "hardcore breaks",
        "hardcore hip hop",
        "hardcore punk",
        "hardcore techno",
        "hardgroove techno",
        "hardstep",
        "hardstyle",
        "hardvapour",
        "hardwave",
        "harsh noise",
        "harsh noise wall",
        "hÃ¡t tuá»ng",
        "hauntology",
        "heartland rock",
        "heaven trap",
        "heavy metal",
        "heavy psych",
        "heikyoku",
        "hexd",
        "hi-nrg",
        "hi-tech",
        "highlife",
        "hill country blues",
        "himene tarava",
        "hindustani classical",
        "hip hop",
        "hip hop soul",
        "hip house",
        "hiplife",
        "honky tonk",
        "honkyoku",
        "hopepunk",
        "horror punk",
        "horror synth",
        "horrorcore",
        "house",
        "huapango",
        "huayno",
        "humppa",
        "hyangak",
        "hybrid trap",
        "hyperpop",
        "hyphy",
        "hypnagogic pop",
        "idm",
        "idol kayÅ",
        "illbient",
        "impressionism",
        "indian pop",
        "indie folk",
        "indie pop",
        "indie rock",
        "indie surf",
        "indietronica",
        "indorock",
        "industrial",
        "industrial hardcore",
        "industrial hip hop",
        "industrial metal",
        "industrial musical",
        "industrial rock",
        "industrial techno",
        "instrumental",
        "instrumental hip hop",
        "instrumental jazz",
        "instrumental rock",
        "interview",
        "irish folk",
        "italo dance",
        "italo house",
        "italo-disco",
        "izlan",
        "j-core",
        "j-pop",
        "j-rock",
        "jÃ¡cara",
        "jaipongan",
        "jam band",
        "jamaican ska",
        "james bay fiddling",
        "jamgrass",
        "jangle pop",
        "javanese gamelan",
        "jazz",
        "jazz blues",
        "jazz fusion",
        "jazz poetry",
        "jazz pop",
        "jazz rap",
        "jazz rock",
        "jazz-funk",
        "jazzstep",
        "jeongak",
        "jerk rap",
        "jersey club",
        "jersey sound",
        "jiangnan sizhu",
        "jit",
        "jiuta",
        "joik",
        "jongo",
        "joropo",
        "jÅruri",
        "jota",
        "jovem guarda",
        "jug band",
        "jÃ¹jÃº",
        "juke",
        "jump blues",
        "jump up",
        "jumpstyle",
        "jungle",
        "jungle dutch",
        "jungle terror",
        "junkanoo",
        "k-pop",
        "kabarett",
        "kacapi suling",
        "kadongo kamu",
        "kafi",
        "kagura",
        "kalindula",
        "kaneka",
        "kantan chamorrita",
        "kanto",
        "kapuka",
        "kaseko",
        "kasÃ©kÃ²",
        "kawaii future bass",
        "kawaii metal",
        "kayÅkyoku",
        "kecak",
        "keroncong",
        "khrueang sai",
        "khyal",
        "kidumbak",
        "kilapanga",
        "kirtan",
        "kizomba",
        "klapa",
        "kleinkunst",
        "klezmer",
        "kliningan",
        "kÃ¶nsrock",
        "koplo",
        "korean ballad",
        "korean revolutionary opera",
        "kouta",
        "krakowiak",
        "krautrock",
        "kuda lumping",
        "kuduro",
        "kujawiak",
        "kulintang",
        "kumi-daiko",
        "kumiuta",
        "kundiman",
        "kwaito",
        "kwassa kwassa",
        "kwela",
        "laiko",
        "lambada",
        "latin",
        "latin ballad",
        "latin disco",
        "latin funk",
        "latin house",
        "latin jazz",
        "latin pop",
        "latin rock",
        "latin soul",
        "lecture",
        "leftfield",
        "lento violento",
        "levenslied",
        "liedermacher",
        "liquid funk",
        "liscio",
        "lo-fi",
        "lo-fi hip hop",
        "lo-fi house",
        "lolicore",
        "louisiana blues",
        "lounge",
        "lovers rock",
        "lowercase",
        "luk krung",
        "luk thung",
        "lundu",
        "lute song",
        "madchester",
        "maddahi",
        "madrigal",
        "maftirim",
        "mahori",
        "mahraganat",
        "mainstream rock",
        "makina",
        "makossa",
        "malagueÃ±a venezolana",
        "malay gamelan",
        "malhun",
        "mallsoft",
        "maloya",
        "mambo",
        "mandopop",
        "manele",
        "mangue beat",
        "manila sound",
        "manyao",
        "marabi",
        "maracatu",
        "march",
        "marching band",
        "marchinha",
        "mariachi",
        "marinera",
        "marrabenta",
        "martial industrial",
        "mashcore",
        "maskanda",
        "mass",
        "math pop",
        "math rock",
        "mathcore",
        "maxixe",
        "mazurka",
        "mbalax",
        "mbaqanga",
        "mbube",
        "medieval",
        "medieval metal",
        "medieval rock",
        "meiji shinkyoku",
        "melbourne bounce",
        "melodic black metal",
        "melodic death metal",
        "melodic dubstep",
        "melodic hardcore",
        "melodic metalcore",
        "melodic techno",
        "melodic trance",
        "memphis rap",
        "mento",
        "merecumbÃ©",
        "merengue",
        "merenhouse",
        "merequetengue",
        "mÃ©ringue",
        "metal",
        "metalcore",
        "meyxana",
        "miami bass",
        "microhouse",
        "microsound",
        "midtempo bass",
        "midwest emo",
        "miejski folk",
        "milonga",
        "min'yÅ",
        "minatory",
        "mincecore",
        "minimal drum and bass",
        "minimal synth",
        "minimal techno",
        "minimal wave",
        "minimalism",
        "minneapolis sound",
        "mobb music",
        "mod",
        "mod revival",
        "moda de viola",
        "modal jazz",
        "modern blues",
        "modern classical",
        "modern hardtek",
        "mood kayÅ",
        "moogsploitation",
        "moombahcore",
        "moombahton",
        "mor lam",
        "mor lam sing",
        "morna",
        "moroccan chaabi",
        "motet",
        "motown",
        "moutya",
        "movimiento alterado",
        "mpb",
        "mugham",
        "muiÃ±eira",
        "mulatÃ³s",
        "muliza",
        "murga",
        "murga uruguaya",
        "musette",
        "music hall",
        "mÃºsica de intervenÃ§Ã£o",
        "musical",
        "musique concrÃ¨te",
        "muziki wa dansi",
        "nagauta",
        "narcocorrido",
        "narodnozabavna glasba",
        "nasheed",
        "nashville sound",
        "nature sounds",
        "nederbeat",
        "nederpop",
        "neo kyma",
        "neo soul",
        "neo-acoustic",
        "neo-medieval folk",
        "neo-progressive rock",
        "neo-psychedelia",
        "neo-rockabilly",
        "neo-traditional country",
        "neoclassical dark wave",
        "neoclassical metal",
        "neoclassical new age",
        "neoclassicism",
        "neocrust",
        "neofolk",
        "neoperreo",
        "nerdcore",
        "nerdcore techno",
        "neue deutsche hÃ¤rte",
        "neue deutsche welle",
        "neurofunk",
        "neurohop",
        "new age",
        "new beat",
        "new jack swing",
        "new orleans blues",
        "new orleans r&b",
        "new rave",
        "new romantic",
        "new wave",
        "ngoma",
        "nháº¡c vÃ ng",
        "nightcore",
        "nigun",
        "nintendocore",
        "nitzhonot",
        "njuup",
        "no wave",
        "nocturne",
        "noh",
        "noise",
        "noise pop",
        "noise rock",
        "noisecore",
        "non-music",
        "nortec",
        "norteÃ±o",
        "northern soul",
        "nouveau zydeco",
        "nova canÃ§Ã³",
        "novelty piano",
        "novo dub",
        "nu disco",
        "nu jazz",
        "nu metal",
        "nu skool breaks",
        "nu style gabber",
        "nueva canciÃ³n",
        "nueva canciÃ³n chilena",
        "nueva canciÃ³n espaÃ±ola",
        "nueva cumbia chilena",
        "nueva trova",
        "nuevo cancionero",
        "nuevo flamenco",
        "nuevo tango",
        "nwobhm",
        "nyÅ« myÅ«jikku",
        "oberek",
        "occult rock",
        "odissi classical",
        "oi",
        "old school death metal",
        "old school hip hop",
        "old-time",
        "onda nueva",
        "ondÅ",
        "onkyo",
        "opera",
        "opera-ballet",
        "operatic pop",
        "orchestral",
        "orchestral jazz",
        "oriental ballad",
        "outlaw country",
        "outsider house",
        "Ã¶zgÃ¼n mÃ¼zik",
        "p-funk",
        "pachanga",
        "pacific reggae",
        "pagan black metal",
        "pagan folk",
        "pagodÃ£o",
        "pagode",
        "pagode romÃ¢ntico",
        "paisley underground",
        "palm-wine",
        "pansori",
        "parang",
        "partido alto",
        "pasillo",
        "pasodoble",
        "payada",
        "peak time techno",
        "pep band",
        "persian pop",
        "philly club",
        "philly soul",
        "phleng phuea chiwit",
        "phonk",
        "piano blues",
        "piano rock",
        "picopop",
        "piedmont blues",
        "pilÃ³n",
        "pimba",
        "pinpeat",
        "pÃ¬obaireachd",
        "pipe band music",
        "piphat",
        "piseiro",
        "piyyut",
        "pizzica",
        "plainchant",
        "plena",
        "plugg",
        "pluggnb",
        "plunderphonics",
        "poetry",
        "political hip hop",
        "polka",
        "polonaise",
        "pon-chak disco",
        "pop",
        "pop ghazal",
        "pop metal",
        "pop punk",
        "pop raÃ¯",
        "pop rap",
        "pop rock",
        "pop soul",
        "pop yeh-yeh",
        "porn groove",
        "pornogrind",
        "porro",
        "post-bop",
        "post-britpop",
        "post-classical",
        "post-grunge",
        "post-hardcore",
        "post-industrial",
        "post-metal",
        "post-minimalism",
        "post-punk",
        "post-punk revival",
        "post-rock",
        "power electronics",
        "power metal",
        "power noise",
        "power pop",
        "power soca",
        "powerviolence",
        "prank calls",
        "production music",
        "progressive",
        "progressive bluegrass",
        "progressive breaks",
        "progressive country",
        "progressive electronic",
        "progressive folk",
        "progressive house",
        "progressive metal",
        "progressive pop",
        "progressive psytrance",
        "progressive rock",
        "progressive trance",
        "proto-punk",
        "psybient",
        "psychedelic",
        "psychedelic folk",
        "psychedelic pop",
        "psychedelic rock",
        "psychedelic soul",
        "psychobilly",
        "psycore",
        "psystyle",
        "psytrance",
        "pub rock",
        "punk",
        "punk blues",
        "punk rap",
        "punk rock",
        "punta",
        "punto",
        "purple sound",
        "q-pop",
        "qaraami",
        "qasidah modern",
        "qawwali",
        "quan há»",
        "queercore",
        "quiet storm",
        "quyi",
        "r&b",
        "rabiz",
        "raga rock",
        "ragga",
        "ragga hip-hop",
        "ragga jungle",
        "raggacore",
        "ragtime",
        "raÃ¯",
        "ranchera",
        "rap metal",
        "rap rock",
        "rapcore",
        "rapso",
        "rara",
        "rasin",
        "rasqueado cuiabano",
        "rasteirinha",
        "rautalanka",
        "rave",
        "rawphoric",
        "rawstyle",
        "rebetiko",
        "red dirt",
        "red song",
        "reductionism",
        "reggae",
        "reggae-pop",
        "reggaeton",
        "regional mexicano",
        "renaissance",
        "repente",
        "requiem",
        "rhumba",
        "riddim dubstep",
        "rigsar",
        "riot grrrl",
        "ripsaw",
        "ritual ambient",
        "rizitika",
        "rkt",
        "rock",
        "rock and roll",
        "rock andaluz",
        "rock andino",
        "rock musical",
        "rock opera",
        "rock urbano",
        "rockabilly",
        "rocksteady",
        "rÅkyoku",
        "rom kbach",
        "romanian popcorn",
        "romantic classical",
        "roots reggae",
        "roots rock",
        "rumba",
        "rumba catalana",
        "rumba cubana",
        "rumba flamenca",
        "runo song",
        "russian chanson",
        "russian romance",
        "ryÅ«kÅka",
        "sacred harp",
        "sacred steel",
        "saeta",
        "salegy",
        "salsa",
        "salsa choke",
        "salsa dura",
        "salsa romÃ¡ntica",
        "saluang klasik",
        "samba",
        "samba de breque",
        "samba de gafieira",
        "samba de roda",
        "samba de terreiro",
        "samba soul",
        "samba-canÃ§Ã£o",
        "samba-choro",
        "samba-enredo",
        "samba-exaltaÃ§Ã£o",
        "samba-jazz",
        "samba-joia",
        "samba-reggae",
        "samba-rock",
        "sambalanÃ§o",
        "sambass",
        "sanjo",
        "santÃ© engagÃ©",
        "sarala gee",
        "sardana",
        "sasscore",
        "sawt",
        "saya afroboliviana",
        "schlager",
        "schottische",
        "schranz",
        "screamo",
        "scrumpy and western",
        "sea shanty",
        "sean-nÃ³s",
        "seapunk",
        "sÃ©ga",
        "seggae",
        "seguidilla",
        "semba",
        "semi-trot",
        "serialism",
        "sertanejo",
        "sertanejo raiz",
        "sertanejo romÃ¢ntico",
        "sertanejo universitÃ¡rio",
        "seto leelo",
        "sevdalinka",
        "sevillanas",
        "shaabi",
        "shan'ge",
        "shangaan electro",
        "shanto",
        "shashmaqam",
        "shatta",
        "shibuya-kei",
        "shidaiqu",
        "shima-uta",
        "shinkyoku",
        "shoegaze",
        "shÅmyÅ",
        "sierreÃ±o",
        "sinawi",
        "singeli",
        "singer-songwriter",
        "ska",
        "ska punk",
        "skacore",
        "skate punk",
        "sketch comedy",
        "skiffle",
        "skiladiko",
        "skinhead reggae",
        "skullstep",
        "skweee",
        "slack-key guitar",
        "slacker rock",
        "slam death metal",
        "slam poetry",
        "slap house",
        "slow waltz",
        "slowcore",
        "sludge metal",
        "smooth jazz",
        "smooth soul",
        "snap",
        "soca",
        "soft rock",
        "sÅkyoku",
        "son calentano",
        "son cubano",
        "son huasteco",
        "son istmeÃ±o",
        "son jarocho",
        "son montuno",
        "songo",
        "sophisti-pop",
        "soukous",
        "soul",
        "soul blues",
        "soul jazz",
        "sound art",
        "sound collage",
        "sound effects",
        "sound poetry",
        "southern gospel",
        "southern hip hop",
        "southern metal",
        "southern rock",
        "southern soul",
        "sovietwave",
        "space age pop",
        "space ambient",
        "space disco",
        "space rock",
        "space rock revival",
        "spacesynth",
        "spectralism",
        "speech",
        "speed garage",
        "speed house",
        "speed metal",
        "speedcore",
        "spirituals",
        "splittercore",
        "spoken word",
        "spouge",
        "standup comedy",
        "steampunk",
        "stenchcore",
        "stoner metal",
        "stoner rock",
        "stornello",
        "street punk",
        "stride",
        "sufi rock",
        "sufiana kalam",
        "sundanese pop",
        "sungura",
        "suomisaundi",
        "surf",
        "surf punk",
        "surf rock",
        "sutartinÄs",
        "swamp blues",
        "swamp pop",
        "swamp rock",
        "swing",
        "swing revival",
        "symphonic black metal",
        "symphonic metal",
        "symphonic prog",
        "symphonic rock",
        "symphony",
        "synth funk",
        "synth-pop",
        "synthwave",
        "taarab",
        "tajaraste",
        "takamba",
        "talempong",
        "talking blues",
        "tallava",
        "tamborera",
        "tamborito",
        "tammurriata",
        "tango",
        "taquirari",
        "tarantella",
        "tarraxinha",
        "tassu",
        "tchinkoumÃ©",
        "tech house",
        "tech trance",
        "technical death metal",
        "technical thrash metal",
        "techno",
        "techno bass",
        "techno kayÅ",
        "technobanda",
        "techstep",
        "tecnobrega",
        "tecnorumba",
        "teen pop",
        "tejano",
        "tembang cianjuran",
        "terrorcore",
        "tex-mex",
        "texas blues",
        "texas country",
        "third stream",
        "third wave ska",
        "thrash metal",
        "thrashcore",
        "thumri",
        "tiento",
        "timba",
        "timbila",
        "tizita",
        "tonada potosina",
        "tonadilla",
        "tondero",
        "township bubblegum",
        "township jive",
        "tradi-modern",
        "traditional black gospel",
        "traditional country",
        "traditional doom metal",
        "trallalero",
        "trance",
        "trance metal",
        "trancestep",
        "trap",
        "trap edm",
        "trap metal",
        "trap shaabi",
        "tread",
        "tribal ambient",
        "tribal guarachero",
        "tribal house",
        "trip hop",
        "tropical house",
        "tropical rock",
        "tropicÃ¡lia",
        "tropipop",
        "trot",
        "trova",
        "trova yucateca",
        "truck driving country",
        "tsapiky",
        "tsonga disco",
        "tsugaru-jamisen",
        "tumba",
        "tumba francesa",
        "tumbÃ©lÃ©",
        "turbo-folk",
        "turntablism",
        "twee pop",
        "twerk",
        "uk drill",
        "uk funky",
        "uk garage",
        "uk hardcore",
        "uk street soul",
        "uk82",
        "underground hip hop",
        "unyago",
        "upopo",
        "uptempo hardcore",
        "urban cowboy",
        "urtiin duu",
        "urumi melam",
        "utopian virtual",
        "uzun hava",
        "v-pop",
        "vallenato",
        "vals criollo",
        "vanera",
        "vaportrap",
        "vaporwave",
        "vaudeville",
        "vaudeville blues",
        "verbunkos",
        "vietnamese bolero",
        "viking metal",
        "viking rock",
        "vinahouse",
        "visa",
        "visual kei",
        "vocal house",
        "vocal jazz",
        "vocal surf",
        "vocal trance",
        "volkstÃ¼mliche musik",
        "waka",
        "waltz",
        "war metal",
        "wassoulou",
        "waulking song",
        "wave",
        "weightless",
        "west coast hip hop",
        "west coast swing",
        "western",
        "western swing",
        "winter synth",
        "witch house",
        "wong shadow",
        "wonky",
        "wonky techno",
        "world fusion",
        "xote",
        "yacht rock",
        "yakousei",
        "yaravÃ­",
        "yayue",
        "yÃ©-yÃ©",
        "yodeling",
        "yu-mex",
        "yue opera",
        "yukar",
        "zamacueca",
        "zamba",
        "zamrock",
        "zarzuela",
        "zeuhl",
        "zeybek",
        "zhongguo feng",
        "ziglibithy",
        "zinli",
        "znamenny chant",
        "zoblazo",
        "zohioliin duu",
        "zolo",
        "zouglou",
        "zouk",
        "zouk love",
        "zydeco",
    };

    public static bool IsKnownGenre(string? value)
    {
        return !string.IsNullOrWhiteSpace(value) && Genres.Contains(value.Trim());
    }
}